// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNN6QhXgwgzNYz_AGZUcVrXiasncbDu8w',
    appId: '1:791496585110:web:47552a9aa816925c66f7b7',
    messagingSenderId: '791496585110',
    projectId: 'car-go-cz-1-st-prod',
    authDomain: 'car-go-cz-1-st-prod.firebaseapp.com',
    storageBucket: 'car-go-cz-1-st-prod.firebasestorage.app',
    measurementId: 'G-ZBEKGLB6F9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkf1mIOSh9ZAigJWMDI9GbZB7PQ7VKhsU',
    appId: '1:791496585110:android:d62542536b24e88e66f7b7',
    messagingSenderId: '791496585110',
    projectId: 'car-go-cz-1-st-prod',
    storageBucket: 'car-go-cz-1-st-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEM-75GSgs632k8UFJVdpquD3DTc8gUM4',
    appId: '1:791496585110:ios:73bb7646439160c966f7b7',
    messagingSenderId: '791496585110',
    projectId: 'car-go-cz-1-st-prod',
    storageBucket: 'car-go-cz-1-st-prod.firebasestorage.app',
    iosBundleId: 'cz.in.cargo.driver',
  );
}
